export type CreativeOrigin = 'fully-human' | 'human-directed' | 'collaboration' | 'ai-generated';

export interface CreativeOriginInfo {
  id: CreativeOrigin;
  label: string;
  shortLabel: string;
  description: string;
  color: string;
  icon: string;
  percentage: string;
}

export const CREATIVE_ORIGINS: CreativeOriginInfo[] = [
  {
    id: 'fully-human',
    label: 'Fully Human',
    shortLabel: 'Human',
    description: 'Created entirely by human hands and mind. No AI tools used in any part of the creative process.',
    color: '#22c55e',
    icon: '✋',
    percentage: '100% Human',
  },
  {
    id: 'human-directed',
    label: 'Human-Directed',
    shortLabel: 'Directed',
    description: 'Human conceived, designed, and directed the work. AI used as a tool under human creative control.',
    color: '#d4a847',
    icon: '🎯',
    percentage: '70-99% Human',
  },
  {
    id: 'collaboration',
    label: 'Human-AI Collaboration',
    shortLabel: 'Collab',
    description: 'Significant creative contribution from both human and AI. Iterative process with meaningful human curation.',
    color: '#a855f7',
    icon: '🤝',
    percentage: '30-70% Human',
  },
  {
    id: 'ai-generated',
    label: 'AI-Generated',
    shortLabel: 'AI',
    description: 'Primarily generated by AI systems. Human contribution limited to prompting, selection, or minor editing.',
    color: '#ec4899',
    icon: '🤖',
    percentage: '0-30% Human',
  },
];

export type WorkType =
  | 'visual-art'
  | 'digital-art'
  | 'photography'
  | 'music'
  | 'writing'
  | 'film-video'
  | 'textile'
  | 'sculpture'
  | 'performance'
  | 'cultural-heritage'
  | 'design'
  | 'other';

export interface WorkTypeInfo {
  id: WorkType;
  label: string;
  icon: string;
}

export const WORK_TYPES: WorkTypeInfo[] = [
  { id: 'visual-art', label: 'Visual Art', icon: '🎨' },
  { id: 'digital-art', label: 'Digital Art', icon: '💻' },
  { id: 'photography', label: 'Photography', icon: '📷' },
  { id: 'music', label: 'Music', icon: '🎵' },
  { id: 'writing', label: 'Writing', icon: '✍️' },
  { id: 'film-video', label: 'Film / Video', icon: '🎬' },
  { id: 'textile', label: 'Textile / Craft', icon: '🧵' },
  { id: 'sculpture', label: 'Sculpture', icon: '🗿' },
  { id: 'performance', label: 'Performance', icon: '🎭' },
  { id: 'cultural-heritage', label: 'Cultural Heritage', icon: '🏛️' },
  { id: 'design', label: 'Design', icon: '✏️' },
  { id: 'other', label: 'Other', icon: '📦' },
];

export interface Certificate {
  id: string;
  title: string;
  description: string;
  workType: WorkType;
  creativeOrigin: CreativeOrigin;
  creatorName: string;
  creatorEmail?: string;
  culturalContext?: string;
  aiToolsUsed?: string;
  humanContribution?: string;
  fileHash?: string;
  fileName?: string;
  fileSize?: number;
  processNotes?: string;
  hash: string;
  timestamp: string;
  createdAt: string;
  verified: boolean;
  views: number;
}

export interface DashboardStats {
  totalCerts: number;
  totalViews: number;
  verifiedCount: number;
}
